### ISSUE TITLE
date field appears to be the same as urldate on the two examples given

### ISSUE THREAD

**Issue by JudicialDomicide** [dmstern/html2biblatex#13]
Using MacOS
Brave Browser

Expected: date = {2020-05-12}
```
@Online {AustralianRentersAreOrganizingToFightEvictionsJustLikeTheyDidinthe1930s-2021-02-02,
  title = {Australian Renters Are Organizing To Fight Evictions, Just Like They Did in the 1930s},
  date = {2021-02-02},
  year = {2021},
  file = {:./references/2020-12-australian-renters-evictions-organizing-1930s-covid.html:html},
  url = {https://jacobinmag.com/2020/12/australian-renters-evictions-organizing-1930s-covid},
  urldate = {2021-02-02}
}
```
=====

Expected: date = {2015-04-22}

```
@Online {EvictingIndigenousAustraliansfromtheirhomelandsisadeclarationofwarIndigenousAustraliansTheGuardian-2021-02-02,
  title = {Evicting Indigenous Australians from their homelands is a declaration of war | Indigenous Australians | The Guardian},
  date = {2021-02-02},
  year = {2021},
  file = {:./references/commentisfree-2015-apr-22-by-evicting-the-homelands-australia-has-again-declared-war-on-indigenous-people.html:html},
  url = {https://www.theguardian.com/commentisfree/2015/apr/22/by-evicting-the-homelands-australia-has-again-declared-war-on-indigenous-people},
  urldate = {2021-02-02}
}
```

Also I just noticed both authors are missing. Perhaps I'm doing something wrong?

**Comment by JudicialDomicide** [comment]
adding a third example here using a medium.com article : author is correctly showing on this but the date is still the same as urldate.

Expected date = {2020-03-20}


```
@Online {TowardsanEmergencyHousingResponsetoCOVID19inGeorgiabyGeorgiaHousingandLegalScholarsMedium-2021-02-02,
  title = {Towards an Emergency Housing Response to COVID-19 in Georgia | by Georgia Housing and Legal Scholars | Medium},
  date = {2021-02-02},
  year = {2021},
  author = {Georgia Housing and Legal Scholars},
  file = {:./references/@elora.raymond-towards-an-emergency-housing-response-to-covid-19-in-georgia-8f05c54f26d3.html:html},
  url = {https://medium.com/@elora.raymond/towards-an-emergency-housing-response-to-covid-19-in-georgia-8f05c54f26d3},
  urldate = {2021-02-02}
}
```

**Comment by dmstern** [comment]
Hey @JudicialDomicide, thank you for reporting this issue!

Unfortunately, I can only get the date information that are provided in the meta data of the page. The information that every page provides is the `lastModified` date. Pages that are frequently modified (e.g. with ads) display the current visitation date as `lastModified`.

The good news is: I managed to add an other option for date recognition, so the Guardian example and the Medium example should now displayed correctly, if you update your bookmarklet with the [latest version](https://raw.githubusercontent.com/dmstern/html2biblatex/master/dist/bookmark-url.js).

The jacobinmag.com website does not provide any parsable date information, so here you might still need some manual finetuning.

**Comment by JudicialDomicide** [comment]
Thank you so much for this. I retested the above and also many others just quickly including bbc articles that were not working before. They are all working now on the whole. Perfect. Thanks very much. 

Quick question: Not related to this issue. Is it easy to change your script to have Author = {Surname, Firstname} or {{Name of Institution}}

Thanks again for this tool. Its very useful for me.

**Comment by dmstern** [comment]
Thank you for this heartwarming feedback! :)

> Is it easy to change your script to have Author = {Surname, Firstname} or {{Name of Institution}}

Unfortunately, this is not easy since page creators can put any string into the author meta data field as far as I know , so we have to take what we get. ;)
If you find a hint how to achieve this, let me know.
