### ISSUE TITLE
Suggestion: Make the tool omit empty fields & make its output multiline & more

### ISSUE THREAD

**Issue by dusekdan** [dmstern/html2biblatex#2]
Hi, I recently started using this bookmark to simplify my work with LaTeX and I would have few suggestions.
- It would be really nice if the bookmark could omit empty fields, eg. when quoting website without author, it would not fill it to the result output as author = {}, 
- Its output would be nice to be multiline, so I would not have to manually add line-breaks to the .bib file after pasting output of your script
- It could escape 'dangerous' characters such are '_', '&' and else, so it does not create output that is not translatable. 

Thanks in advance for considering any of the mentioned and updating the script.

**Comment by dmstern** [comment]
Hi dusekdan,
thank you for you suggestions! :)

> Its output would be nice to be multiline, so I would not have to manually add line-breaks to the .bib file after pasting output of your script
> For a more beautiful output see README: https://github.com/dmstern/html2biblatex#formatting-biblatex-entry
> 
> It could escape 'dangerous' characters such are '_', '&' and else, so it does not create output that is not translatable.
> It would be really nice if the bookmark could omit empty fields, eg. when quoting website without author, it would not fill it to the result output as author = {},

Good advise, thanks! I'll do this if I find the time... or you can do pull of push request (I'm not sure which is correct ;)).

**Comment by dmstern** [comment]
Implemented all three suggestions:
https://github.com/dmstern/html2biblatex/commit/72975f0fe836b1c629f980cc537c61ba0681df7b
https://github.com/dmstern/html2biblatex/commit/ce07572757e30861ba64ca3baa6482dd486b2887
https://github.com/dmstern/html2biblatex/commit/4b69e7379dc1847794f2d878010240b6dd935427

Would be a pleasure to hear if it works for you. :)
